### ISSUE TITLE
getPayload 404, User Not Found 

### ISSUE THREAD

**Issue by devmaxwel** [Morpher-io/MorpherWallet#135]
I am building on top of this blockchain and recently I faced an error when signing up or signing in('getPayload 404 error User not found'). I have tried to debug any possible error but I am not able to. 

What can I do.

**Comment by tomw1808** [comment]
Right now the morpher-wallet is for self-hosting only, we do not offer a hosted solution for third party websites (yet). An example of how the hosting looks like, is morpher itself. We're using the exact wallet for our platform, which you can see when you sign up with us.

@devmaxwel can you elaborate on your use-case please?

**Comment by tomw1808** [comment]
@devmaxwel if you need any further help, just reach out to me via email. I'm genuinely interested in your use-case. Thanks for closing the issue.
